// Decompiled with JetBrains decompiler
// Type: resource_templates
// Assembly: fbs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: EE45F058-4776-4456-92BB-8311B7676A83
// Assembly location: D:\RBS\rbs\rbs\bin\fbs.dll

using ASP;
using skynapse.fbs;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web.Profile;
using System.Web.SessionState;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;

public class resource_templates : fbs_base_page, IRequiresSessionState
{
  protected HtmlAnchor sample_editable_1_new;
  protected Button btnExportExcel;
  protected HiddenField hdn_search;
  protected HiddenField hdn_orderby;
  protected HiddenField hdn_orderdir;
  public string html_table;
  public string Save = "";
  public string delete = "";
  private bool is_admin;

  protected DefaultProfile Profile => (DefaultProfile) this.Context.Profile;

  protected global_asax ApplicationInstance => (global_asax) this.Context.ApplicationInstance;

  protected new void Page_Load(object sender, EventArgs e)
  {
    if (!Convert.ToBoolean(this.current_account.properties["resource_booking"]))
      this.Server.Transfer("~\\unauthorized.aspx");
    try
    {
      foreach (user_group userGroup in this.current_user.groups.Values)
      {
        if (userGroup.group_type == 1)
          this.is_admin = true;
        else if (!this.is_admin)
          this.is_admin = false;
      }
      if (!this.is_admin)
        this.redirect_unauthorized();
      if (this.IsPostBack)
        return;
      try
      {
        if (this.Request.QueryString["action"] == "delete")
        {
          if (this.Request.QueryString["id"] != null)
            this.resapi.delete_resource_template(Convert.ToInt64(this.Request.QueryString["id"].ToString()), this.current_user.account_id, this.current_user.user_id);
        }
      }
      catch (Exception ex)
      {
        fbs_base_page.log.Error((object) "Error ->", ex);
      }
      this.populate_ui();
      if (this.Session["Save"] != null && this.Session["Save"] == (object) "S")
      {
        this.Save = "S";
        this.Session.Remove("Save");
      }
      if (this.Session["delete"] == null)
        return;
      if (this.Session["delete"] == (object) "S")
      {
        this.delete = "S";
        this.Session.Remove("delete");
      }
      else
      {
        if (this.Session["delete"] != (object) "F")
          return;
        this.delete = "F";
        this.Session.Remove("delete");
      }
    }
    catch (Exception ex)
    {
      fbs_base_page.log.Error((object) "Error ->", ex);
    }
  }

  protected void btnExportExcel_Click(object sender, EventArgs e)
  {
    try
    {
      DataSet dataSet = (DataSet) this.ViewState["data"] ?? this.resapi.view_templates(this.current_user.account_id, this.str_resource_module);
      dataSet.Tables[0].Columns.Add("status_string");
      if (dataSet != null)
      {
        List<string> source = new List<string>();
        foreach (DataRow row in (InternalDataCollectionBase) dataSet.Tables[0].Rows)
        {
          if (row["status"].ToString() != "-1" && !((IEnumerable<object>) source).Contains<object>(row["template_name"]))
          {
            string str = "";
            row["template_name"] = (object) row["template_name"].ToString();
            foreach (DataRow dataRow in dataSet.Tables[0].Select("resource_template_id='" + row["resource_template_id"].ToString() + "'"))
              str = str + dataRow["item_name"].ToString() + "(" + dataRow["quantity"].ToString() + " " + dataRow["unit_of_measure"].ToString() + ") <br/>";
            row["item_name"] = (object) row["item_name"].ToString();
            row["status_string"] = !(row["status"].ToString() == "1") ? (object) "NotAvailable" : (object) "Available";
          }
        }
      }
      Dictionary<string, string> dictionary = new Dictionary<string, string>();
      dictionary.Add("template_name", "Name");
      dictionary.Add("item_name", "Items");
      dictionary.Add("status_string", "Status");
      excel excel = new excel();
      excel.file_name = "+ current_user.full_name + " + this.current_timestamp.ToString(api_constants.display_datetime_format) + ".xls";
      excel.footer = "Generated By : " + this.current_user.full_name + "     Generated on :  " + this.tzapi.current_user_timestamp().ToString(api_constants.display_datetime_format);
      excel.data = dataSet;
      excel.column_names = dictionary;
      excel.table_identifier = "+ current_user.full_name + ";
      excel.header = "Resource Templates";
      this.Response.Clear();
      this.Response.AddHeader("content-disposition", "attachment;filename=Resource Templates_" + this.current_timestamp.ToString(api_constants.display_datetime_format) + ".xls");
      this.Response.Charset = "";
      this.Response.ContentType = Resources.fbs.excel_mime_type;
      this.Response.Write(this.exapi.get_excel(excel));
      this.Response.End();
    }
    catch (Exception ex)
    {
      fbs_base_page.log.Error((object) "Error -> ", ex);
    }
  }

  private void populate_ui()
  {
    try
    {
      StringBuilder stringBuilder = new StringBuilder();
      DataSet dataSet = this.resapi.view_templates(this.current_user.account_id, this.str_resource_module);
      this.ViewState.Add("data", (object) dataSet);
      List<string> source = new List<string>();
      foreach (DataRow row in (InternalDataCollectionBase) dataSet.Tables[0].Rows)
      {
        if (row["status"].ToString() != "-1" && !((IEnumerable<object>) source).Contains<object>(row["template_name"]))
        {
          string str = "";
          stringBuilder.Append("<tr>");
          stringBuilder.Append("<td>" + row["template_name"].ToString() + "</td>");
          foreach (DataRow dataRow in dataSet.Tables[0].Select("resource_template_id='" + row["resource_template_id"].ToString() + "'"))
            str = str + dataRow["item_name"].ToString() + "(" + dataRow["quantity"].ToString() + " " + dataRow["unit_of_measure"].ToString() + ") <br/>";
          stringBuilder.Append("<td>" + str + "</td>");
          if (row["status"].ToString() == "1")
            stringBuilder.Append("<td><span class='label label-Available'>Available</span></td>");
          else
            stringBuilder.Append("<td><span class='label label-NotAvailable'>Not Available</span></td>");
          stringBuilder.Append("<td><div class='actions'><div class='bgp'><a class='btn default' href='#' data-toggle='dropdown'><i class='icon-angle-down'></i></a><ul class='ddm p-r'>");
          stringBuilder.Append("<li><a href='resource_template_add_edit.aspx?id=" + row["resource_template_id"].ToString() + "'><i class='icon-pencil'></i> Edit</a></li>");
          stringBuilder.Append("<li><a href='javascript:delete_resource_template(" + row["resource_template_id"].ToString() + ")'><i class='icon-trash'></i> Remove</a></li>");
          stringBuilder.Append("</ul></div></div></td>");
          stringBuilder.Append("</tr>");
          source.Add(row["template_name"].ToString());
        }
      }
      this.html_table = stringBuilder.ToString();
    }
    catch (Exception ex)
    {
      fbs_base_page.log.Error((object) "Error ->", ex);
    }
  }
}
